create_graph_from_PPI:
  PATH_TO_PPI: "Datasets/BIOGRID-ORGANISM-Homo_sapiens-4.4.206.tab3.txt"
  DISEASE_IDs: ['C0006142',  'C0009402', 'C0023893', 'C0036341',  'C0376358', 'C3714756', 'C0860207',  'C0011581', 'C0005586', 'C0001973']
  SCALE_FEATURES: False
  FEATURE_PATH: "Datasets/nedbit_features/"
  FROM_DIAMOND: False #Set to True when using PPI data from DIAMOnD publication
  GRAPH_SAVE_PATH: "Graphs/"

 