create_graph_from_PPI:
  PATH_TO_PPI: "Datasets/BIOGRID-ORGANISM-Homo_sapiens-4.4.206.tab3.txt" #Datasets/Diamond_dataset/diamond_ppi.txt #"Datasets/BIOGRID-ORGANISM-Homo_sapiens-4.4.206.tab3.txt" 
  DISEASE_IDs: ['C0006142', 'C0009402', 'C0023893', 'C0036341',  'C0376358', 'C3714756', 'C0860207',  'C0011581', 'C0005586', 'C0001973'] #['C0006142', 'C0009402', 'C0023893', 'C0036341',  'C0376358', 'C3714756', 'C0860207',  'C0011581', 'C0005586', 'C0001973']
  SCALE_FEATURES: False
  FEATURE_PATH: "Datasets/nedbit_features/" #"Datasets/Diamond_dataset/nedbit_features/" #"Datasets/nedbit_features/"
  FROM_DIAMOND: False #Set to True when using PPI data from DIAMOnD publication
  GRAPH_SAVE_PATH: "Graphs/"

trainer_script:
  SEED: 42
  DISEASE_IDs: ['C0006142',  'C0009402', 'C0023893', 'C0036341',  'C0376358', 'C3714756', 'C0860207',  'C0011581', 'C0005586', 'C0001973']
  MODE: ["multiclass", "binary"] #binary. Multiclass uses pseudo-labels from NIAPU. binary considers unlabeled genes as negative samples.
  FROM_DIAMOND: False #Set to True when using PPI data from DIAMOnD publication
  GRAPH_PATH: "Graphs/graph_nedbit_"
  LEARNING_RATE: 0.001
  EPOCHS: 40000
  WEIGHT_DECAY: 0.0005
  HIDDEN_CHANNELS: 16
  DATASET_PATH: "Datasets/"
  QUARTILES: False #if False, uses labels from NIAPU. If True, divides the pseudo-classes in quartiles. No effect for binary classification.