PATH_TO_DATASETS    = 'Datasets/'
PATH_TO_GRAPHS      = 'Graphs/'
PATH_TO_IMAGES      = 'Images/'
PATH_TO_REPORTS     = 'Reports/'
PATH_TO_MODELS      = 'Models/'
PATH_TO_RANKINGS    = 'Rankings/'
PATH_TO_METRICS			= 'Metrics/'